[2023-07-08T15:34:48.392+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: csv_to_postgres_dag2.create_postgres_table scheduled__2023-01-09T00:00:00+00:00 [queued]>
[2023-07-08T15:34:48.409+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: csv_to_postgres_dag2.create_postgres_table scheduled__2023-01-09T00:00:00+00:00 [queued]>
[2023-07-08T15:34:48.410+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-07-08T15:34:48.545+0000] {taskinstance.py:1327} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2023-01-09 00:00:00+00:00
[2023-07-08T15:34:48.554+0000] {standard_task_runner.py:57} INFO - Started process 144 to run task
[2023-07-08T15:34:48.557+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'csv_to_postgres_dag2', 'create_postgres_table', 'scheduled__2023-01-09T00:00:00+00:00', '--job-id', '99', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpx748p_um']
[2023-07-08T15:34:48.561+0000] {standard_task_runner.py:85} INFO - Job 99: Subtask create_postgres_table
[2023-07-08T15:34:48.631+0000] {task_command.py:410} INFO - Running <TaskInstance: csv_to_postgres_dag2.create_postgres_table scheduled__2023-01-09T00:00:00+00:00 [running]> on host 9aa32a2a42d2
[2023-07-08T15:34:48.721+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='csv_to_postgres_dag2' AIRFLOW_CTX_TASK_ID='create_postgres_table' AIRFLOW_CTX_EXECUTION_DATE='2023-01-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-09T00:00:00+00:00'
[2023-07-08T15:34:48.723+0000] {sql.py:265} INFO - Executing: 
CREATE TABLE reviews (
    reviewer_id INTEGER,
    store_name VARCHAR(255),
    category VARCHAR(255),
    store_address VARCHAR(255),
    latitude FLOAT,
    longitude FLOAT,
    rating_count INTEGER,
    review_time VARCHAR(255),
    review TEXT,
    rating VARCHAR(10)
);
[2023-07-08T15:34:48.733+0000] {base.py:73} INFO - Using connection ID 'postgres_***' for task execution.
[2023-07-08T15:34:48.801+0000] {base.py:73} INFO - Using connection ID 'postgres_***' for task execution.
[2023-07-08T15:34:48.805+0000] {sql.py:375} INFO - Running statement: 
CREATE TABLE reviews (
    reviewer_id INTEGER,
    store_name VARCHAR(255),
    category VARCHAR(255),
    store_address VARCHAR(255),
    latitude FLOAT,
    longitude FLOAT,
    rating_count INTEGER,
    review_time VARCHAR(255),
    review TEXT,
    rating VARCHAR(10)
);, parameters: None
[2023-07-08T15:34:48.807+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 277, in execute
    **extra_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 349, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 380, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.DuplicateTable: relation "reviews" already exists

[2023-07-08T15:34:48.820+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=csv_to_postgres_dag2, task_id=create_postgres_table, execution_date=20230109T000000, start_date=20230708T153448, end_date=20230708T153448
[2023-07-08T15:34:48.839+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 99 for task create_postgres_table (relation "reviews" already exists
; 144)
[2023-07-08T15:34:48.890+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-08T15:34:49.038+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-07-08T15:43:05.135+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: csv_to_postgres_dag2.create_postgres_table scheduled__2023-01-09T00:00:00+00:00 [queued]>
[2023-07-08T15:43:05.152+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: csv_to_postgres_dag2.create_postgres_table scheduled__2023-01-09T00:00:00+00:00 [queued]>
[2023-07-08T15:43:05.153+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-07-08T15:43:05.175+0000] {taskinstance.py:1327} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2023-01-09 00:00:00+00:00
[2023-07-08T15:43:05.183+0000] {standard_task_runner.py:57} INFO - Started process 234 to run task
[2023-07-08T15:43:05.189+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'csv_to_postgres_dag2', 'create_postgres_table', 'scheduled__2023-01-09T00:00:00+00:00', '--job-id', '175', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpf18vl05z']
[2023-07-08T15:43:05.193+0000] {standard_task_runner.py:85} INFO - Job 175: Subtask create_postgres_table
[2023-07-08T15:43:05.273+0000] {task_command.py:410} INFO - Running <TaskInstance: csv_to_postgres_dag2.create_postgres_table scheduled__2023-01-09T00:00:00+00:00 [running]> on host 9aa32a2a42d2
[2023-07-08T15:43:05.408+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='csv_to_postgres_dag2' AIRFLOW_CTX_TASK_ID='create_postgres_table' AIRFLOW_CTX_EXECUTION_DATE='2023-01-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-09T00:00:00+00:00'
[2023-07-08T15:43:05.411+0000] {sql.py:265} INFO - Executing: 
CREATE TABLE reviews (
    reviewer_id INTEGER,
    store_name VARCHAR(255),
    category VARCHAR(255),
    store_address VARCHAR(255),
    latitude FLOAT,
    longitude FLOAT,
    rating_count INTEGER,
    review_time VARCHAR(255),
    review TEXT,
    rating VARCHAR(10)
);
[2023-07-08T15:43:05.425+0000] {base.py:73} INFO - Using connection ID 'postgres_***' for task execution.
[2023-07-08T15:43:05.523+0000] {base.py:73} INFO - Using connection ID 'postgres_***' for task execution.
[2023-07-08T15:43:05.529+0000] {sql.py:375} INFO - Running statement: 
CREATE TABLE reviews (
    reviewer_id INTEGER,
    store_name VARCHAR(255),
    category VARCHAR(255),
    store_address VARCHAR(255),
    latitude FLOAT,
    longitude FLOAT,
    rating_count INTEGER,
    review_time VARCHAR(255),
    review TEXT,
    rating VARCHAR(10)
);, parameters: None
[2023-07-08T15:43:05.532+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 277, in execute
    **extra_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 349, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 380, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.DuplicateTable: relation "reviews" already exists

[2023-07-08T15:43:05.547+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=csv_to_postgres_dag2, task_id=create_postgres_table, execution_date=20230109T000000, start_date=20230708T154305, end_date=20230708T154305
[2023-07-08T15:43:05.711+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 175 for task create_postgres_table (relation "reviews" already exists
; 234)
[2023-07-08T15:43:05.762+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-08T15:43:05.791+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
