[2023-07-08T15:34:46.849+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: csv_to_postgres_dag2.create_postgres_table scheduled__2023-01-01T00:00:00+00:00 [queued]>
[2023-07-08T15:34:46.868+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: csv_to_postgres_dag2.create_postgres_table scheduled__2023-01-01T00:00:00+00:00 [queued]>
[2023-07-08T15:34:46.869+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-07-08T15:34:46.895+0000] {taskinstance.py:1327} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2023-01-01 00:00:00+00:00
[2023-07-08T15:34:46.903+0000] {standard_task_runner.py:57} INFO - Started process 113 to run task
[2023-07-08T15:34:46.910+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'csv_to_postgres_dag2', 'create_postgres_table', 'scheduled__2023-01-01T00:00:00+00:00', '--job-id', '89', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpqeff28he']
[2023-07-08T15:34:46.914+0000] {standard_task_runner.py:85} INFO - Job 89: Subtask create_postgres_table
[2023-07-08T15:34:46.989+0000] {task_command.py:410} INFO - Running <TaskInstance: csv_to_postgres_dag2.create_postgres_table scheduled__2023-01-01T00:00:00+00:00 [running]> on host 9aa32a2a42d2
[2023-07-08T15:34:47.096+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='csv_to_postgres_dag2' AIRFLOW_CTX_TASK_ID='create_postgres_table' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T00:00:00+00:00'
[2023-07-08T15:34:47.099+0000] {sql.py:265} INFO - Executing: 
CREATE TABLE reviews (
    reviewer_id INTEGER,
    store_name VARCHAR(255),
    category VARCHAR(255),
    store_address VARCHAR(255),
    latitude FLOAT,
    longitude FLOAT,
    rating_count INTEGER,
    review_time VARCHAR(255),
    review TEXT,
    rating VARCHAR(10)
);
[2023-07-08T15:34:47.125+0000] {base.py:73} INFO - Using connection ID 'postgres_***' for task execution.
[2023-07-08T15:34:47.211+0000] {base.py:73} INFO - Using connection ID 'postgres_***' for task execution.
[2023-07-08T15:34:47.217+0000] {sql.py:375} INFO - Running statement: 
CREATE TABLE reviews (
    reviewer_id INTEGER,
    store_name VARCHAR(255),
    category VARCHAR(255),
    store_address VARCHAR(255),
    latitude FLOAT,
    longitude FLOAT,
    rating_count INTEGER,
    review_time VARCHAR(255),
    review TEXT,
    rating VARCHAR(10)
);, parameters: None
[2023-07-08T15:34:47.219+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 277, in execute
    **extra_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 349, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 380, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.DuplicateTable: relation "reviews" already exists

[2023-07-08T15:34:47.235+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=csv_to_postgres_dag2, task_id=create_postgres_table, execution_date=20230101T000000, start_date=20230708T153446, end_date=20230708T153447
[2023-07-08T15:34:47.256+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 89 for task create_postgres_table (relation "reviews" already exists
; 113)
[2023-07-08T15:34:47.282+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-08T15:34:47.445+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-07-08T15:43:02.673+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: csv_to_postgres_dag2.create_postgres_table scheduled__2023-01-01T00:00:00+00:00 [queued]>
[2023-07-08T15:43:02.691+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: csv_to_postgres_dag2.create_postgres_table scheduled__2023-01-01T00:00:00+00:00 [queued]>
[2023-07-08T15:43:02.692+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-07-08T15:43:02.714+0000] {taskinstance.py:1327} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2023-01-01 00:00:00+00:00
[2023-07-08T15:43:02.723+0000] {standard_task_runner.py:57} INFO - Started process 170 to run task
[2023-07-08T15:43:02.733+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'csv_to_postgres_dag2', 'create_postgres_table', 'scheduled__2023-01-01T00:00:00+00:00', '--job-id', '154', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpuuvsngb6']
[2023-07-08T15:43:02.741+0000] {standard_task_runner.py:85} INFO - Job 154: Subtask create_postgres_table
[2023-07-08T15:43:02.856+0000] {task_command.py:410} INFO - Running <TaskInstance: csv_to_postgres_dag2.create_postgres_table scheduled__2023-01-01T00:00:00+00:00 [running]> on host 9aa32a2a42d2
[2023-07-08T15:43:03.023+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='csv_to_postgres_dag2' AIRFLOW_CTX_TASK_ID='create_postgres_table' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T00:00:00+00:00'
[2023-07-08T15:43:03.035+0000] {sql.py:265} INFO - Executing: 
CREATE TABLE reviews (
    reviewer_id INTEGER,
    store_name VARCHAR(255),
    category VARCHAR(255),
    store_address VARCHAR(255),
    latitude FLOAT,
    longitude FLOAT,
    rating_count INTEGER,
    review_time VARCHAR(255),
    review TEXT,
    rating VARCHAR(10)
);
[2023-07-08T15:43:03.051+0000] {base.py:73} INFO - Using connection ID 'postgres_***' for task execution.
[2023-07-08T15:43:03.151+0000] {base.py:73} INFO - Using connection ID 'postgres_***' for task execution.
[2023-07-08T15:43:03.158+0000] {sql.py:375} INFO - Running statement: 
CREATE TABLE reviews (
    reviewer_id INTEGER,
    store_name VARCHAR(255),
    category VARCHAR(255),
    store_address VARCHAR(255),
    latitude FLOAT,
    longitude FLOAT,
    rating_count INTEGER,
    review_time VARCHAR(255),
    review TEXT,
    rating VARCHAR(10)
);, parameters: None
[2023-07-08T15:43:03.161+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 277, in execute
    **extra_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 349, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 380, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.DuplicateTable: relation "reviews" already exists

[2023-07-08T15:43:03.177+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=csv_to_postgres_dag2, task_id=create_postgres_table, execution_date=20230101T000000, start_date=20230708T154302, end_date=20230708T154303
[2023-07-08T15:43:03.195+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 154 for task create_postgres_table (relation "reviews" already exists
; 170)
[2023-07-08T15:43:03.228+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-08T15:43:03.268+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
