[2023-07-08T15:34:47.165+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: csv_to_postgres_dag2.create_postgres_table scheduled__2023-01-02T00:00:00+00:00 [queued]>
[2023-07-08T15:34:47.182+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: csv_to_postgres_dag2.create_postgres_table scheduled__2023-01-02T00:00:00+00:00 [queued]>
[2023-07-08T15:34:47.182+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-07-08T15:34:47.202+0000] {taskinstance.py:1327} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2023-01-02 00:00:00+00:00
[2023-07-08T15:34:47.210+0000] {standard_task_runner.py:57} INFO - Started process 119 to run task
[2023-07-08T15:34:47.214+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'csv_to_postgres_dag2', 'create_postgres_table', 'scheduled__2023-01-02T00:00:00+00:00', '--job-id', '90', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmptbisjyqt']
[2023-07-08T15:34:47.217+0000] {standard_task_runner.py:85} INFO - Job 90: Subtask create_postgres_table
[2023-07-08T15:34:47.291+0000] {task_command.py:410} INFO - Running <TaskInstance: csv_to_postgres_dag2.create_postgres_table scheduled__2023-01-02T00:00:00+00:00 [running]> on host 9aa32a2a42d2
[2023-07-08T15:34:47.386+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='csv_to_postgres_dag2' AIRFLOW_CTX_TASK_ID='create_postgres_table' AIRFLOW_CTX_EXECUTION_DATE='2023-01-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-02T00:00:00+00:00'
[2023-07-08T15:34:47.387+0000] {sql.py:265} INFO - Executing: 
CREATE TABLE reviews (
    reviewer_id INTEGER,
    store_name VARCHAR(255),
    category VARCHAR(255),
    store_address VARCHAR(255),
    latitude FLOAT,
    longitude FLOAT,
    rating_count INTEGER,
    review_time VARCHAR(255),
    review TEXT,
    rating VARCHAR(10)
);
[2023-07-08T15:34:47.397+0000] {base.py:73} INFO - Using connection ID 'postgres_***' for task execution.
[2023-07-08T15:34:47.569+0000] {base.py:73} INFO - Using connection ID 'postgres_***' for task execution.
[2023-07-08T15:34:47.579+0000] {sql.py:375} INFO - Running statement: 
CREATE TABLE reviews (
    reviewer_id INTEGER,
    store_name VARCHAR(255),
    category VARCHAR(255),
    store_address VARCHAR(255),
    latitude FLOAT,
    longitude FLOAT,
    rating_count INTEGER,
    review_time VARCHAR(255),
    review TEXT,
    rating VARCHAR(10)
);, parameters: None
[2023-07-08T15:34:47.581+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 277, in execute
    **extra_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 349, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 380, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.DuplicateTable: relation "reviews" already exists

[2023-07-08T15:34:47.600+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=csv_to_postgres_dag2, task_id=create_postgres_table, execution_date=20230102T000000, start_date=20230708T153447, end_date=20230708T153447
[2023-07-08T15:34:47.619+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 90 for task create_postgres_table (relation "reviews" already exists
; 119)
[2023-07-08T15:34:47.667+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-08T15:34:47.935+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-07-08T15:43:03.335+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: csv_to_postgres_dag2.create_postgres_table scheduled__2023-01-02T00:00:00+00:00 [queued]>
[2023-07-08T15:43:03.355+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: csv_to_postgres_dag2.create_postgres_table scheduled__2023-01-02T00:00:00+00:00 [queued]>
[2023-07-08T15:43:03.356+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-07-08T15:43:03.382+0000] {taskinstance.py:1327} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2023-01-02 00:00:00+00:00
[2023-07-08T15:43:03.394+0000] {standard_task_runner.py:57} INFO - Started process 183 to run task
[2023-07-08T15:43:03.399+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'csv_to_postgres_dag2', 'create_postgres_table', 'scheduled__2023-01-02T00:00:00+00:00', '--job-id', '158', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpk27m4ug2']
[2023-07-08T15:43:03.404+0000] {standard_task_runner.py:85} INFO - Job 158: Subtask create_postgres_table
[2023-07-08T15:43:03.490+0000] {task_command.py:410} INFO - Running <TaskInstance: csv_to_postgres_dag2.create_postgres_table scheduled__2023-01-02T00:00:00+00:00 [running]> on host 9aa32a2a42d2
[2023-07-08T15:43:03.602+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='csv_to_postgres_dag2' AIRFLOW_CTX_TASK_ID='create_postgres_table' AIRFLOW_CTX_EXECUTION_DATE='2023-01-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-02T00:00:00+00:00'
[2023-07-08T15:43:03.603+0000] {sql.py:265} INFO - Executing: 
CREATE TABLE reviews (
    reviewer_id INTEGER,
    store_name VARCHAR(255),
    category VARCHAR(255),
    store_address VARCHAR(255),
    latitude FLOAT,
    longitude FLOAT,
    rating_count INTEGER,
    review_time VARCHAR(255),
    review TEXT,
    rating VARCHAR(10)
);
[2023-07-08T15:43:03.615+0000] {base.py:73} INFO - Using connection ID 'postgres_***' for task execution.
[2023-07-08T15:43:03.705+0000] {base.py:73} INFO - Using connection ID 'postgres_***' for task execution.
[2023-07-08T15:43:03.711+0000] {sql.py:375} INFO - Running statement: 
CREATE TABLE reviews (
    reviewer_id INTEGER,
    store_name VARCHAR(255),
    category VARCHAR(255),
    store_address VARCHAR(255),
    latitude FLOAT,
    longitude FLOAT,
    rating_count INTEGER,
    review_time VARCHAR(255),
    review TEXT,
    rating VARCHAR(10)
);, parameters: None
[2023-07-08T15:43:03.713+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 277, in execute
    **extra_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 349, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 380, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.DuplicateTable: relation "reviews" already exists

[2023-07-08T15:43:03.730+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=csv_to_postgres_dag2, task_id=create_postgres_table, execution_date=20230102T000000, start_date=20230708T154303, end_date=20230708T154303
[2023-07-08T15:43:03.749+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 158 for task create_postgres_table (relation "reviews" already exists
; 183)
[2023-07-08T15:43:03.774+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-08T15:43:03.805+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
